config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users
  resources :asset_sims, only: [:create, :update, :destroy]
  get "events/change_income", to: "events#change_income"
  resources :events, only: [:new, :create, :update, :edit, :destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :asset_sim
  validates :name, presence: true, length: { maximum: 255 }
  validates :age, presence: true, numericality: { only_integer: true, in: 0..100 }
  validates :value, presence: true, numericality: { only_integer: true }
  validates :term, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :description, length: { maximum: 255 }
  validates :isvalid, presence: true
  validates :event_type, presence: true, numericality: { only_integer: true, in: 0..10 }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_asset_sim, only: [:edit, :update, :destroy]

  def new
    @event = Event.new
  end

  def change_income
    @event = Event.new
  end

  def create
    @asset_sim = current_user.asset_sims.find_by(user_id: current_user.id)
    unless @asset_sim
      redirect_to root_url
    end
    @event = @asset_sim.events.build(event_params)

    if @event.save
      flash[:success] = "正常に設定されました"
      redirect_to root_url
    else
      flash.now[:danger] = "イベントが設定できませんでした"
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:success] = "正常に更新されました"
      redirect_to root_url
    else
      flash.now[:danger] = "更新されませんでした"
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    flash[:success] = "正常に削除されました"
    redirect_to root_url
  end

  # Strong Parameter
  def event_params
    params.require(:event).permit(:name, :value, :age, :term, :description, :isvalid, :event_type)
  end

  def correct_asset_sim
    @asset_sim = current_user.asset_sims.find_by(user_id: current_user.id) #検索方法は見直し
    unless @asset_sim
      redirect_to root_url
    end
  end
end

app/views/events/_form.html.erb
<div class="row border rounded">
  <div class="col-sm-8 offset-sm-2">

    <%= form_with(model: @event) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
      <%= f.hidden_field :event_type, :value => type %>
      <%= f.hidden_field :isvalid, :value => true %>
      <div class="mb-3">
        <%= f.label :name, "イベント名" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <% if type == Constants::EVENT_TYPE_OTHER %>
        <div class="mb-3">
          <%= f.label :value, "収支[万円]" %>
          <%= f.text_field :value, class: "form-control" %>
        </div>
      <% end %>
      <% if type == Constants::EVENT_TYPE_CHANGE_INCOME %>
        <div class="mb-3">
          <%= f.label :value, "収入[万円]" %>
          <%= f.text_field :value, class: "form-control" %>
        </div>
      <% end %>
      <div class="mb-3">
        <%= f.label :age, "イベント発生時の年齢" %>
        <%= f.text_field :age, class: "form-control" %>
      </div>
      <% if type == Constants::EVENT_TYPE_OTHER %>
        <div class="mb-3">
          <%= f.label :term, "期間[年]" %>
          <%= f.text_field :term, class: "form-control" %>
        </div>
      <% else %>
         <%= f.hidden_field :term, :value => 0 %>
      <% end %>
      <div class="mb-3">
        <%= f.label :description, "説明" %>
        <%= f.text_field :description, class: "form-control" %>
      </div>
      <%= f.submit "設定", class: "btn btn-primary w-100" %>
    <% end %>
  </div>
</div>

app/views/events/_nav.html.erb
<div class="col-sm-8">
  <ul class="nav nav-tabs nav-justified">
    <li class="nav-item">
      <a href="<%= new_event_path %>" class="nav-link 
      <%= "active" if current_page?(new_event_path) %>">
        イベント設定
      </a>
    </li>
    <li class="nav-item">
      <a href="<%= events_change_income_path %>" class="nav-link 
      <%= "active" if current_page?(events_change_income_path) %>">
        収入変更
      </a>
    </li>
  </ul>
</div>

app/views/events/change_income.html.erb
<%= render "nav" %>
<%= render "form", event: @event, type: Constants::EVENT_TYPE_CHANGE_INCOME %>

app/views/events/edit.html.erb
<h1><%= @event.name %></h1>
<%= render "form", event: @event, type: @event.event_type %>

app/views/events/new.html.erb
<%= render "nav" %>
<%= render "form", event: @event, type: Constants::EVENT_TYPE_OTHER %>