config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users
  resources :asset_sims, only: [:create, :update, :destroy]
  get "events/change_income", to: "events#change_income"
  resources :events, only: [:new, :create, :update, :edit, :destroy]
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    Struct.new("Chkbox", :name, :ischecked)

    if logged_in?
      @asset_sim = current_user.asset_sims.find_or_initialize_by(user_id: current_user.id) #検索方法はあとで見直し
      @pagy, @asset_sims = pagy(current_user.asset_sims.order(id: :desc))

      unless @asset_sim.new_record?
        @pagy, @events = pagy(@asset_sim.events.order(id: :desc))
        @events = @asset_sim.events.order(id: :desc)

        @chkboxes = {
          chk_asset: Struct::Chkbox.new("資産", true),
          chk_cash: Struct::Chkbox.new("現金", true),
          chk_investment_asset: Struct::Chkbox.new("投資資産", true),
          chk_income: Struct::Chkbox.new("年間収入", true),
          chk_expense: Struct::Chkbox.new("年間支出", true),
        }

        create_graph_asset
      end
    end
  end

  private

  def create_graph_asset
    age_max = 80

    #設定値で初期値設定
    @cash = @asset_sim.cash
    @investment_asset = @asset_sim.investment_asset
    @income = @asset_sim.income
    @expense = @asset_sim.expense

    #グラフ描画データ初期化
    @graph = {
      chk_asset: [],
      chk_cash: [],
      chk_investment_asset: [],
      chk_income: [],
      chk_expense: [],
    }

    #実行ボタン押下時のみグラフ表示設定を更新する
    if params[:isButtonDown]
      set_chkbox
    end

    for i in 0..(age_max - current_user.age)
      age = current_user.age + i
      inc_income = 0
      inc_expense = 0

      #年度のイベントの期間中の収支を計算
      @events.each do |event|
        case event.event_type
        when Constants::EVENT_TYPE_CHANGE_INCOME
          if event.isvalid && event.age == age
            @income = event.value
          end
        when Constants::EVENT_TYPE_OTHER
          if event.isvalid && event.age <= age && age < event.age + event.term
            if event.value >= 0
              inc_income = inc_income + event.value
            else
              inc_expense = inc_expense - event.value
            end
          end
        end
      end
      annual_income = @income + inc_income
      annual_expense = @expense - inc_expense

      annual_balance = annual_income - annual_expense

      add_graph(:chk_asset, [age.to_s, @cash + @investment_asset])
      add_graph(:chk_cash, [age.to_s, @cash])
      add_graph(:chk_investment_asset, [age.to_s, @investment_asset])
      add_graph(:chk_income, [age.to_s, annual_income])
      add_graph(:chk_expense, [age.to_s, annual_expense])

      cal_next_year(annual_balance)
      i += 1
    end
  end

  def set_chkbox
    @events.each do |event|
      if params[:isvalid[event.id]] == event.id.to_s
        event.isvalid = true
      else
        event.isvalid = false
      end
      event.update_attribute(:isvalid, event.isvalid)
    end

    @chkboxes.each do |key, chkbox|
      if params[key].to_i == 0
        chkbox.ischecked = false
      else
        chkbox.ischecked = true
      end
    end
  end

  def add_graph(key, value)
    if @chkboxes[key].ischecked
      @graph[key] << value
    end
  end

  def cal_next_year(annual_balance)
    #年間収支が黒字の場合
    if (annual_balance) >= 0
      #投資割合で現金と投資資産を増額
      @cash = @cash + (annual_balance) * (@asset_sim.investment_ratio.to_f / 100)
      @investment_asset = @investment_asset * (1 + (@asset_sim.investment_yield / 100)) + (annual_balance) * ((100 - @asset_sim.investment_ratio).to_f / 100)
      #年間収支が赤字の場合
    else
      #現金があり、年間支出を足してマイナスとならない場合は現金からマイナス
      if @cash + (annual_balance) >= 0
        @cash = @cash + (annual_balance)
        @investment_asset = @investment_asset * (1 + (@asset_sim.investment_yield / 100))
        #現金がない場合は投資資産からマイナス
      elsif @investment_asset + annual_balance >= 0
        @investment_asset = @investment_asset + (annual_balance)
        @investment_asset = @investment_asset * (1 + (@asset_sim.investment_yield / 100))
      else #現金も投資資産もない場合は現金からマイナス
        @cash = @cash + (annual_balance)
      end
    end
    #インフレ率に応じて年間支出増加
    @expense = @expense * (1 + (@asset_sim.inflation_ratio / 100))
  end
end

app/views/toppages/_form_asset_sim.html.erb
<div class="row">
  <div class="col-sm-8 offset-sm-2">

    <%= form_with(model: @asset_sim) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :cash, '現金[万円]' %>
        <%= f.text_field :cash, class: 'form-control' %>
      </div>
      
      <div class="mb-3">
        <%= f.label :investment_asset, '投資資産[万円]' %>
        <%= f.text_field :investment_asset, class: 'form-control' %>
      </div>
      
      <div class="mb-3">
        <%= f.label :income, '年収[万円]' %>
        <%= f.text_field :income, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :expense, '年間支出[万円]' %>
        <%= f.text_field :expense, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :investment_ratio, '投資割合[%]' %>
        <%= f.text_field :investment_ratio, class: 'form-control' %>
      </div>
      
      <div class="mb-3">
        <%= f.label :investment_yield, '投資利回り[%]' %>
        <%= f.text_field :investment_yield, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :inflation_ratio, 'インフレ率[%]' %>
        <%= f.text_field :inflation_ratio, class: 'form-control' %>
      </div>

      <%= f.submit '設定', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-sm-3">
      <%= render "form_asset_sim" %>
    </div>
    <div class="col-sm-9">
      <% unless @asset_sim.new_record? %>
        <%= form_with url: root_path, method: :get, local: true do |f| %>
          <div class="row">
            <div>
              <ul class="list-group list-group-horizontal">
                <% @chkboxes.each do |key, chkbox| %>  
                  <li class="list-group-item" style="border: none">
                    <%= f.check_box key, checked: chkbox.ischecked %>
                    <%= f.label key, chkbox.name %>
                  </li>
                <% end %> 
              </ul>
            </div>
          </div>  
          <%= line_chart [
                           { name: @chkboxes[:chk_asset].name, data: @graph[:chk_asset] },
                           { name: @chkboxes[:chk_cash].name, data: @graph[:chk_cash] },
                           { name: @chkboxes[:chk_investment_asset].name, data: @graph[:chk_investment_asset] },
                           { name: @chkboxes[:chk_income].name, data: @graph[:chk_income] },
                           { name: @chkboxes[:chk_expense].name, data: @graph[:chk_expense] },
                         ] %>      
          <% if @events.any? %>
            <table class="table table-striped">
              <thread>
                <tr class= "row">
                  <th class= "col-1">有効</th>
                  <th class= "col-5">イベント名</th>
                  <th class= "col-1">収支</th>
                  <th class= "col-1">年齢</th>
                  <th class= "col-1">期間</th>
                  <th class= "col-3"></th>
                </tr>
              </thread>
              <tbody>
                <% @events.each do |event| %>  
                  <tr class= "row">
                    <td class= col-1><%= check_box_tag :isvalid[event.id], event.id, event.isvalid %></td>
                    <td class= col-5><%= event.name %></td>
                    <td class= col-1><%= event.value %></td>
                    <td class= col-1><%= event.age %></td>
                    <td class= col-1><%= event.term %></td>
                    <td class= col-3>
                      <%= link_to "編集", edit_event_path(event), class: "btn btn-dark btn-sm" %>
                      <%= link_to "削除", event, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-danger btn-sm" %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <%== pagy_bootstrap_nav(@pagy) %>
          <% end %>
          <div class="row">
            <div class="actions col-3">
              <%= f.hidden_field :isButtonDown, :value => true %>
              <%= f.submit "シミュレーション実行", class: "btn btn-dark w-30" %>
            </div>
            <div class= col-3>
              <%= link_to "イベント設定", new_event_path, class: "btn btn-dark w-30" %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="bg-secondary p-3 p-sm-5 my-4 rounded">
    <div class="text-center text-white">
      <h1>Life Plan Sim</h1>
      <%= link_to "ユーザー登録", new_user_path, class: "btn btn-lg btn-primary" %>
    </div>
  </div>
<% end %>